### ISSUE TITLE
Jump Command Improvement

### ISSUE THREAD

**Issue by ShockerAttack01** [ThatsNotM3/HelpfulCommands#2]
### Describe your Suggestion

Add another param that is a boolean that checks for blocks in the way

### Proposed Changes

This param would look something like this |/jump 5 true| the true means it will check for blocks and wont teleport you past the blocks you are looking at while the false version would allow you to teleport past the blocks in the way

**Comment by expecticament** [comment]
This feature was added in [Release 3.1.0](https://github.com/Expecticament/HelpfulCommands/releases/tag/3.1.0). 1.20.1 build will be uploaded later. Thanks for your help in improving the mod!
