### ISSUE TITLE
Jump command cant jump without value

### ISSUE THREAD

**Issue by ShockerAttack01** [ThatsNotM3/HelpfulCommands#3]
### Describe the Bug

typing /jump alone won't teleport you to the block you are looking at instead you get an error

### To Reproduce

type /jump

### Expected behavior

teleports me to the block

### Mod Info

mod version 2.0.0 game version 1.20.1 running on fabric

**Comment by expecticament** [comment]
This issue has been fixed in a newer version of the mod - [3.0.0a-preview5](https://github.com/Expecticament/HelpfulCommands/releases/tag/3.0.0a-preview5) (currently the latest version for Fabric 1.20.1).

Version 2.x will no longer receive updates.
