### ISSUE TITLE
Option to show or not show output in main chat

### ISSUE THREAD

**Issue by ShockerAttack01** [ThatsNotM3/HelpfulCommands#4]
### Describe your Suggestion

When using a command like /jump or /lighting where ever you get teleported to or strike lightning to it pops up the coords in chat it would be nice if there was a way to turn it off completely for all commands or indivual

### Proposed Changes

you can have this as another arguement for the /hc config command so it could look like this /hc config manageCommand (specified command) toggleCommandOutput or /hc config manageGlobalCommandOutput (boolean value) or it could be both

**Comment by expecticament** [comment]
This is redundant, as there is a `sendCommandFeedback` gamerule in the base game that Helpful Commands respects (as of 3.x). You can achieve the desired behavior by simply setting the above gamerule to `false`. Hope this helps!
