### ISSUE TITLE
1.21.2-1.21.3 support

### ISSUE THREAD

**Issue by boldandbrad** [ThatsNotM3/HelpfulCommands#9]
### Describe your Suggestion

The latest release only supports 1.21.1 but I'd love to update my server to 1.21.3. The other few mods I use have already been updated, but I cannot yet update it since using the 1.21.1 version of this mod causes the server to immediately fail with the latest fabric api and 1.21.3 server jar.

### Proposed Changes

Assuming the datapacks etc in 1.21.2 and 1.21.3 do not have breaking changes that affect this mod, simply re-publish a version that is compatible with those versions.

If there are breaking changes, then perhaps some minor tweaks to the codebase would be required.

**Comment by expecticament** [comment]
You can now download Helpful Commands 3.2.0 for Minecraft 1.21.2-1.21.3 from the [Releases](https://github.com/Expecticament/HelpfulCommands/releases/tag/3.2.0) page. Please let me know if there are any issues with this version!

**Comment by boldandbrad** [comment]
Awesome! I'll check it out tonight. Happy Halloween 🎃

**Comment by expecticament** [comment]
Thank you! Same to you :D

**Comment by boldandbrad** [comment]
Works!
